import React from "react";
import Head from "next/head";
import Header from "./header";
import Footer from "./footer";
import { Container } from "@mui/material";
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles({
    page: {
        background: '#f9f9f9',
        maxWidth: '100%'
    }
})

function Layout({children}){
    const classes = useStyles();

    return(
        <>
            <Head>
                <title>Renner Challenge Next.js</title>
                <meta name="description" content="Generated by created next app" />
                <link rel="icon" href="/logo.ico"/>        
            </Head>
            <Header />
            <Container >
                    {children}
            </Container>
            <Footer />
        </>
    )
}

export default Layout;