import { Provider } from 'react-redux';
import React from 'react';
import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';
import store from '../redux/store';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
        <Head>
          <title>Renner Challenge Next.js</title>
          <meta name="description" content="Generated by created next app" />
          <link rel="icon" href="/logo.ico"/>        
        </Head>
        <Header />
          <React.StrictMode>
          <Component {...pageProps} />
          </React.StrictMode>
        <Footer />
    </Provider>
  )
}

export default MyApp
